// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reserve_status_enum", new[] { "blocked", "booking", "canceled", "confirmed", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "shift_enum", new[] { "afternoon", "morning", "night" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.Account.AccountModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("registration");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.HasIndex("Registration", "UserName", "Email")
                        .HasAnnotation("Npgsql:TsVectorConfig", "portuguese");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Registration", "UserName", "Email"), "GIN");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Models.AccountSubjectModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FkAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fk_account_id");

                    b.Property<long>("FkSubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_subject_id");

                    b.HasKey("Id");

                    b.HasIndex("FkSubjectId");

                    b.HasIndex("FkAccountId", "FkSubjectId")
                        .IsUnique();

                    b.ToTable("account_subject");
                });

            modelBuilder.Entity("Models.Reserve.ResourceReserveModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FkAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fk_account_id");

                    b.Property<long>("FkResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_resource_id");

                    b.Property<long>("FkSpaceReserveId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_space_reserve_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purpose");

                    b.HasKey("Id");

                    b.HasIndex("FkAccountId");

                    b.HasIndex("FkResourceId");

                    b.HasIndex("FkSpaceReserveId");

                    b.ToTable("resource_reserve");
                });

            modelBuilder.Entity("Models.Reserve.SpaceReserveModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("FkAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fk_account_id");

                    b.Property<long>("FkSpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_space_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purpose");

                    b.Property<EReserveStatus>("Status")
                        .HasColumnType("reserve_status_enum")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FkAccountId");

                    b.HasIndex("FkSpaceId");

                    b.ToTable("space_reserve");
                });

            modelBuilder.Entity("Models.Resource.ResourceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanReserve")
                        .HasColumnType("boolean")
                        .HasColumnName("can_reserve");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("resource");
                });

            modelBuilder.Entity("Models.Schedule.ScheduleModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<TimeOnly>("EndAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_at");

                    b.Property<EShift>("Shift")
                        .HasColumnType("shift_enum")
                        .HasColumnName("shift");

                    b.Property<TimeOnly>("StartAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_at");

                    b.HasKey("Id");

                    b.ToTable("schedule");
                });

            modelBuilder.Entity("Models.SpaceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Name", "Description")
                        .HasAnnotation("Npgsql:TsVectorConfig", "portuguese");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name", "Description"), "GIN");

                    b.ToTable("space");
                });

            modelBuilder.Entity("Models.SpaceReserveScheduleModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FkScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_schedule_id");

                    b.Property<long>("FkSpaceReserveId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_space_reserve_id");

                    b.HasKey("Id");

                    b.HasIndex("FkScheduleId");

                    b.HasIndex("FkSpaceReserveId", "FkScheduleId")
                        .IsUnique();

                    b.ToTable("space_reserve_schedule");
                });

            modelBuilder.Entity("Models.SpaceResourceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FkResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_resource_id");

                    b.Property<long>("FkSpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_space_id");

                    b.HasKey("Id");

                    b.HasIndex("FkResourceId");

                    b.HasIndex("FkSpaceId", "FkResourceId")
                        .IsUnique();

                    b.ToTable("space_resource");
                });

            modelBuilder.Entity("Models.SpaceSubjectModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FkSpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_space_id");

                    b.Property<long>("FkSubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("fk_subject_id");

                    b.HasKey("Id");

                    b.HasIndex("FkSubjectId");

                    b.HasIndex("FkSpaceId", "FkSubjectId")
                        .IsUnique();

                    b.ToTable("space_subject");
                });

            modelBuilder.Entity("Models.Subject.SubjectModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("subject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Models.Account.AccountModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Models.Account.AccountModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Account.AccountModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Models.Account.AccountModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.AccountSubjectModel", b =>
                {
                    b.HasOne("Models.Account.AccountModel", "Account")
                        .WithMany("AccountSubjects")
                        .HasForeignKey("FkAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Subject.SubjectModel", "Subject")
                        .WithMany("AccountSubjects")
                        .HasForeignKey("FkSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Models.Reserve.ResourceReserveModel", b =>
                {
                    b.HasOne("Models.Account.AccountModel", "Account")
                        .WithMany("ResourceReserves")
                        .HasForeignKey("FkAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Resource.ResourceModel", "Resource")
                        .WithMany()
                        .HasForeignKey("FkResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Reserve.SpaceReserveModel", "SpaceReserve")
                        .WithMany("ResourceReserves")
                        .HasForeignKey("FkSpaceReserveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Resource");

                    b.Navigation("SpaceReserve");
                });

            modelBuilder.Entity("Models.Reserve.SpaceReserveModel", b =>
                {
                    b.HasOne("Models.Account.AccountModel", "Account")
                        .WithMany("SpaceReserves")
                        .HasForeignKey("FkAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.SpaceModel", "Space")
                        .WithMany("SpaceReserves")
                        .HasForeignKey("FkSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Models.SpaceReserveScheduleModel", b =>
                {
                    b.HasOne("Models.Schedule.ScheduleModel", "Schedule")
                        .WithMany()
                        .HasForeignKey("FkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Reserve.SpaceReserveModel", "Space")
                        .WithMany("SpaceReserveSchedules")
                        .HasForeignKey("FkSpaceReserveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Models.SpaceResourceModel", b =>
                {
                    b.HasOne("Models.Resource.ResourceModel", "Resource")
                        .WithMany("SpaceResources")
                        .HasForeignKey("FkResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.SpaceModel", "Space")
                        .WithMany("SpaceResources")
                        .HasForeignKey("FkSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Models.SpaceSubjectModel", b =>
                {
                    b.HasOne("Models.SpaceModel", "Space")
                        .WithMany("SpaceSubjects")
                        .HasForeignKey("FkSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Subject.SubjectModel", "Subject")
                        .WithMany("SpaceSubjects")
                        .HasForeignKey("FkSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Models.Account.AccountModel", b =>
                {
                    b.Navigation("AccountSubjects");

                    b.Navigation("ResourceReserves");

                    b.Navigation("SpaceReserves");
                });

            modelBuilder.Entity("Models.Reserve.SpaceReserveModel", b =>
                {
                    b.Navigation("ResourceReserves");

                    b.Navigation("SpaceReserveSchedules");
                });

            modelBuilder.Entity("Models.Resource.ResourceModel", b =>
                {
                    b.Navigation("SpaceResources");
                });

            modelBuilder.Entity("Models.SpaceModel", b =>
                {
                    b.Navigation("SpaceReserves");

                    b.Navigation("SpaceResources");

                    b.Navigation("SpaceSubjects");
                });

            modelBuilder.Entity("Models.Subject.SubjectModel", b =>
                {
                    b.Navigation("AccountSubjects");

                    b.Navigation("SpaceSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
