CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(32) NOT NULL,
    email varchar(320) NOT NULL,
    registration varchar(16) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role varchar(16) NOT NULL,
    enabled BOOLEAN DEFAULT false,
    created_at DATE NOT NULL DEFAULT now()
);

CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    FOREIGN KEY (fk_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(32) NOT NULL UNIQUE
);

CREATE TABLE user_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user_id BIGINT NOT NULL,
    fk_subject_id INT NOT NULL,
    FOREIGN KEY (fk_user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (fk_subject_id) REFERENCES subject(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_subject UNIQUE (fk_user_id, fk_subject_id)
);

CREATE TABLE space (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) UNIQUE NOT NULL,
    description varchar(256),
    capacity INT NOT NULL,
    locked BOOLEAN DEFAULT TRUE
);

CREATE TABLE space_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_space_id INT NOT NULL,
    fk_subject_id INT NOT NULL,
    FOREIGN KEY (fk_space_id) REFERENCES space(id) ON DELETE CASCADE,
    FOREIGN KEY (fk_subject_id) REFERENCES subject(id) ON DELETE CASCADE,
    CONSTRAINT uq_space_subject UNIQUE (fk_space_id, fk_subject_id)
);

CREATE TABLE resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL UNIQUE
);

CREATE TABLE space_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_space_id INT NOT NULL,
    fk_resource_id INT NOT NULL,
    FOREIGN KEY (fk_space_id) REFERENCES space(id),
    FOREIGN KEY (fk_resource_id) REFERENCES resource(id),
    CONSTRAINT uq_space_resource UNIQUE (fk_space_id, fk_resource_id)
);

CREATE TYPE schedule_enum AS ENUM (
    'M_AULA_1', 'M_AULA_2', 'M_AULA_3', 'M_AULA_4', 'M_AULA_5',
    'V_AULA_1', 'V_AULA_2', 'V_AULA_3', 'V_AULA_4', 'V_AULA_5',
    'N_AULA_1', 'N_AULA_2', 'N_AULA_3', 'N_AULA_4'
);

CREATE TYPE schedule_status_enum AS ENUM (
    'CONFIRMED',
    'PENDING',
    'ABSENT',
    'LOCKED',
    'CANCELED'
);

CREATE TABLE reserve (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT NOW(),
    reserved_date_from DATE NOT NULL,
    reserved_date_to DATE NOT NULL,
    status schedule_status_enum DEFAULT 'CONFIRMED',
    purpose VARCHAR(100) NOT NULL,
    fk_user_id BIGINT NOT NULL,
    fk_space_id BIGINT NOT NULL,
    FOREIGN KEY (fk_user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (fk_space_id) REFERENCES space(id) ON DELETE CASCADE
);

CREATE TABLE reserve_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule schedule_enum NOT NULL,
    fk_reserve_id BIGINT NOT NULL,
    FOREIGN KEY (fk_reserve_id) REFERENCES reserve(id) ON DELETE CASCADE,
    CONSTRAINT uq_space_schedule UNIQUE (fk_reserve_id, schedule)
);